name: Test
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: test
    attributes:
      label: Repos
      description: Please add the repos you wish to add this user to, one per line
  - type: textarea
    id: test2
    attributes:
      label: Repos2
      description: Please add the repos you wish to add this user to, one per line
